{application,combine,
             [{registered,[]},
              {description,"A parser combinator library for Elixir projects."},
              {vsn,"0.8.0"},
              {modules,['Elixir.Combine','Elixir.Combine.Helpers',
                        'Elixir.Combine.ParserState',
                        'Elixir.Combine.Parsers.Base',
                        'Elixir.Combine.Parsers.Binary',
                        'Elixir.Combine.Parsers.Text']},
              {applications,[kernel,stdlib,elixir]}]}.